# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pre < Formula
  desc "Security proxy for package managers"
  homepage "https://github.com/yowainwright/pre"
  version "0.4.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yowainwright/pre/releases/download/v0.4.0/pre-darwin-amd64"
      sha256 "dafb80cd9c3e6f137120c4dfe70411a21189b0d16cb0d8a3a86bb86c92d09510"

      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yowainwright/pre/releases/download/v0.4.0/pre-darwin-arm64"
      sha256 "86698094a221386ea717112d7a4d6ecceff508b9be3c3020072825a533d3e3e4"

      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yowainwright/pre/releases/download/v0.4.0/pre-linux-amd64"
      sha256 "0b507aa4bd562272f04618e8da5a80db80123088f2f142505bb7f5e8e6ed86bc"
      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yowainwright/pre/releases/download/v0.4.0/pre-linux-arm64"
      sha256 "5ddf4b1fdea636ca0ed97a8df57eb1f705dfadeab9710ff2873ee7d4de3ffb3a"
      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
  end

  def caveats
    <<~EOS
      Shell hooks are not installed automatically. To intercept package
      manager commands, run:
        pre setup
    EOS
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pre --version")
    ENV["HOME"] = testpath.to_s
    output = shell_output("#{bin}/pre status")
    assert_match "shell hooks: not installed", output
  end
end
