# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pre < Formula
  desc "Security proxy for package managers"
  homepage "https://github.com/yowainwright/pre"
  version "0.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/yowainwright/pre/releases/download/v0.2.0/pre-darwin-amd64"
      sha256 "63401a10d0f8cfec4859a57b5836c894ea604558a55f2df558ded3d23ca3e10c"

      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/yowainwright/pre/releases/download/v0.2.0/pre-darwin-arm64"
      sha256 "5285ba0621219e0f8faf4851768e06fec36724018dba4e8db7bc2405ce0e5c33"

      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/yowainwright/pre/releases/download/v0.2.0/pre-linux-amd64"
      sha256 "797a949a3015a440fa962bfc4786f9467bb871ca12fc84d27fd7c3b68abc0983"
      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/yowainwright/pre/releases/download/v0.2.0/pre-linux-arm64"
      sha256 "8d4b4480fded38c3fe47412f90f09be5f2a559c15b198f9c5401b12d265d16c5"
      define_method(:install) do
        bin.install Dir["pre-*"].first => "pre"
      end
    end
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pre --version")
  end
end
