# This file was generated by GoReleaser. DO NOT EDIT.
cask "pk" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "e723cc70a0e8acea07b360958ad4ef5b8a78ed98fedd4bb6a19adb7e1950a8eb"
      url "https://github.com/yowainwright/pk/releases/download/v#{version}/pk-darwin-amd64"
      binary "pk-darwin-amd64", target: "pk"
    end
    on_arm do
      sha256 "43291c813d178b755317dccfb733b81996765c055a35a150d5f7f4384ae28a16"
      url "https://github.com/yowainwright/pk/releases/download/v#{version}/pk-darwin-arm64"
      binary "pk-darwin-arm64", target: "pk"
    end
  end

  on_linux do
    on_intel do
      sha256 "b5cd31d81241d76deada08b84611b0ea8f8f4668524ef83ea0a7544254754de7"
      url "https://github.com/yowainwright/pk/releases/download/v#{version}/pk-linux-amd64"
      binary "pk-linux-amd64", target: "pk"
    end
    on_arm do
      sha256 "dacf0f45f5a99d1e084c564553e8c13f700eaa81dfc0513c05781e5eb906eb3e"
      url "https://github.com/yowainwright/pk/releases/download/v#{version}/pk-linux-arm64"
      binary "pk-linux-arm64", target: "pk"
    end
  end

  name "pk"
  desc "Safe-by-default local development process cleanup"
  homepage "https://github.com/yowainwright/pk"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary = Dir["#{staged_path}/pk-darwin-*"].first
      if binary
        quarantine = system_command "/usr/bin/xattr",
                                    args: ["-p", "com.apple.quarantine", binary],
                                    must_succeed: false,
                                    print_stderr: false
        system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", binary] if quarantine.success?
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The macOS binary is checksum-verified but not notarized. This cask
    removes quarantine only from the staged pk binary.
  EOS
end
