# This file was generated by GoReleaser. DO NOT EDIT.
cask "pre" do
  version "0.5.1"

  on_macos do
    on_intel do
      sha256 "39b41fbf6a73166e69b21e45acce04c7caf4347f25e669611dc15f32f37593af"
      url "https://github.com/yowainwright/pre/releases/download/v#{version}/pre-darwin-amd64"
      binary "pre-darwin-amd64", target: "pre"
    end
    on_arm do
      sha256 "3b6ce43161c8f67a6e24b270c6a0fa57e4e28ef19bd5e4356fbe89a6884b9635"
      url "https://github.com/yowainwright/pre/releases/download/v#{version}/pre-darwin-arm64"
      binary "pre-darwin-arm64", target: "pre"
    end
  end

  on_linux do
    on_intel do
      sha256 "b2207f011341b4b420bb000b13df8af3a14fa13429ad4806df52a6b16409b494"
      url "https://github.com/yowainwright/pre/releases/download/v#{version}/pre-linux-amd64"
      binary "pre-linux-amd64", target: "pre"
    end
    on_arm do
      sha256 "c618dd2451013adee89984ab772ce07da1bc35da9d7d129f033dfae8be6724e6"
      url "https://github.com/yowainwright/pre/releases/download/v#{version}/pre-linux-arm64"
      binary "pre-linux-arm64", target: "pre"
    end
  end

  name "pre"
  desc "Security guardrail for package managers"
  homepage "https://github.com/yowainwright/pre"

  livecheck do
    skip "Auto-generated on release."
  end

  postflight do
    if OS.mac?
      binary = Dir["#{staged_path}/pre-darwin-*"].first
      if binary
        quarantine = system_command "/usr/bin/xattr",
                                    args: ["-p", "com.apple.quarantine", binary],
                                    must_succeed: false,
                                    print_stderr: false
        system_command "/usr/bin/xattr", args: ["-d", "com.apple.quarantine", binary] if quarantine.success?
      end
    end
  end

  # No zap stanza required

  caveats <<~EOS
    The macOS binary is checksum-verified but not notarized. This cask
    removes quarantine only from the staged pre binary.

    Shell hooks are not installed automatically. To intercept package
    manager commands, run:
      pre setup
  EOS
end
