# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Codependence < Formula
  desc "Enforce dependency version policy across projects, workspaces, and CI"
  homepage "https://jeffry.in/codependence/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/codependence/releases/download/v1.0.16/codependence-darwin-arm64"
      sha256 "aa136960512b18aa0eca8e419ebae9bea2430ae7f59383eb7714b88717928a4f"
    end

    on_intel do
      url "https://github.com/yowainwright/codependence/releases/download/v1.0.16/codependence-darwin-amd64"
      sha256 "50f26fe25a08c4ae40914a511687bfd7aaa8c175aaac109eb0ea26cab3f6a17e"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/codependence/releases/download/v1.0.16/codependence-linux-arm64"
      sha256 "fa55c02eaa2ae6931791bf0b0c5d6a9d0a646b16dc3cbe30f6e1c107aa2b385a"
    end

    on_intel do
      url "https://github.com/yowainwright/codependence/releases/download/v1.0.16/codependence-linux-amd64"
      sha256 "2640013f5db1933f63936e6da11febd42826f0440320d32ebe0f72a321daab10"
    end
  end

  def install
    bin.install Dir["codependence-*"].first => "codependence"
    bin.install_symlink bin/"codependence" => "cdp"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/codependence --version")
    assert_match version.to_s, shell_output("#{bin}/cdp --version")
  end
end
