# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diu < Formula
  desc "Do I Use - Package Manager Execution Tracker"
  homepage "https://github.com/yowainwright/diu"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/yowainwright/diu/releases/download/v0.1.1/diu_0.1.1_darwin_amd64.tar.gz"
    sha256 "40d20d534b71239dad3c460ca74ac0141ce4c2603f8a260dc59d004ad4c4e9ab"

    def install
      bin.install "diu"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/yowainwright/diu/releases/download/v0.1.1/diu_0.1.1_darwin_arm64.tar.gz"
    sha256 "d66daaa36176b381fe691cf0ab0b84fdc75f48ef6113bce9542d141d91af13f4"

    def install
      bin.install "diu"
    end
  end

  def caveats
    <<~EOS
      DIU stores configuration in ~/.config/diu/config.json
      and execution data in ~/.local/share/diu.

      Quick start:
        diu daemon start
        diu daemon status
    EOS
  end

  test do
    assert_match "diu", shell_output("#{bin}/diu --version")
    system bin/"diu", "--help"
  end
end
