# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Diu < Formula
  desc "Track package-manager and global CLI usage"
  homepage "https://github.com/yowainwright/diu"
  license "MIT"
  revision 1

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/diu/releases/download/v0.2.3/diu_0.2.3_darwin_arm64.tar.gz"
      sha256 "ffd26d142ad51dd6abf8bb8577c4f899547a6867eac8d192485d9eb26b301b89"
    end

    on_intel do
      url "https://github.com/yowainwright/diu/releases/download/v0.2.3/diu_0.2.3_darwin_amd64.tar.gz"
      sha256 "1eb613c13590bd4f15a880f7f34fb33b10a38b843ae053dbf069423306bfe5c9"
    end
  end

  depends_on :macos

  def install
    bin.install "diu"
    pkgshare.install "LICENSE"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/diu --version")
  end
end
