# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Diu < Formula
  desc "Do I Use - Package Manager Execution Tracker"
  homepage "https://github.com/yowainwright/diu"
  version "0.1.1"
  license "MIT"
  depends_on :macos

  if Hardware::CPU.intel?
    url "https://github.com/yowainwright/diu/releases/download/v0.1.1/diu_0.1.1_darwin_amd64.tar.gz"
    sha256 "2f63009f943556dc4f77d9696b449fea5f811e0800ad5daf423c6ce20ea02151"

    def install
      bin.install "diu"
    end
  end
  if Hardware::CPU.arm?
    url "https://github.com/yowainwright/diu/releases/download/v0.1.1/diu_0.1.1_darwin_arm64.tar.gz"
    sha256 "3a3bc6dd8577620ebdfbdf32ecd60b1734b1969ee7d77cf87f3606591726febf"

    def install
      bin.install "diu"
    end
  end

  def caveats
    <<~EOS
      DIU stores configuration in ~/.config/diu/config.json
      and execution data in ~/.local/share/diu.

      Quick start:
        diu daemon start
        diu daemon status
    EOS
  end

  test do
    assert_match "diu", shell_output("#{bin}/diu --version")
    system bin/"diu", "--help"
  end
end
