# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class FsLint < Formula
  desc "Enforce project file and folder structure"
  homepage "https://github.com/yowainwright/fs-lint"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.3.0/fs-lint-darwin-arm64"
      sha256 "cfd44a7d715ff70cd3d33e16f756f530035002bb2206f58afec8db2178997edb"
    end

    on_intel do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.3.0/fs-lint-darwin-amd64"
      sha256 "acb9003f264e9b9436d6955c6ece6a430c54bee6734d6acbcdeb96cb2c359170"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.3.0/fs-lint-linux-arm64"
      sha256 "52f0085c221b7058bf6baff2c349c27a841f376852d3e9cd48982df843b79054"
    end

    on_intel do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.3.0/fs-lint-linux-amd64"
      sha256 "6852523905b35df0548e73907dd35772af76f72abc3cc91e27f50017b40cc5c9"
    end
  end

  def install
    bin.install Dir["fs-lint-*"].first => "fs-lint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fs-lint --version")
  end
end
