# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class FsLint < Formula
  desc "Enforce project file and folder structure"
  homepage "https://github.com/yowainwright/fs-lint"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.0/fs-lint-darwin-arm64"
      sha256 "ad031f425d8f467814ff940b0e009c3afe7e31f8a9547d12b90ae20547266a1f"
    end

    on_intel do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.0/fs-lint-darwin-amd64"
      sha256 "bfef0b61791ea492215e54c649d87a726a55011559d9d6c97d2bc84e6594d1da"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.0/fs-lint-linux-arm64"
      sha256 "b221f264df1359edc56770cf791c609eb9abdce1c24369269b237b8c9eb1b99f"
    end

    on_intel do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.0/fs-lint-linux-amd64"
      sha256 "ad76c3294a581c86d758182624dd247c0a88777ba71220c032c61a9509404072"
    end
  end

  def install
    bin.install Dir["fs-lint-*"].first => "fs-lint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fs-lint --version")
  end
end
