# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class FsLint < Formula
  desc "Enforce project file and folder structure"
  homepage "https://github.com/yowainwright/fs-lint"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.1/fs-lint-darwin-arm64"
      sha256 "433796ef9b34d0accfe54d05fbc51ec4273fd07a6b1e1de3e13cce4aba3ba0ca"
    end

    on_intel do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.1/fs-lint-darwin-amd64"
      sha256 "284d83b7582c4b20d4a94c49df3277528dc1edaf397280f8ae63b10b452e2e33"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.1/fs-lint-linux-arm64"
      sha256 "7f367870bed1a8116b172de512a555b9aeae46f7559f5ef3b5c0858f82d24c56"
    end

    on_intel do
      url "https://github.com/yowainwright/fs-lint/releases/download/v0.2.1/fs-lint-linux-amd64"
      sha256 "8b9c4c222d489765e45be085d3333d02c2d6bd1c847fb068e62bd99363009fd1"
    end
  end

  def install
    bin.install Dir["fs-lint-*"].first => "fs-lint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/fs-lint --version")
  end
end
