# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pastoralist < Formula
  desc "Audit, secure, and clean up package manager overrides"
  homepage "https://jeffry.in/pastoralist/"
  license "MIT"
  revision 1

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.5/pastoralist-darwin-arm64"
      sha256 "f8bb02aaa5b46c16da9dced3579d7c297f83ececc2b8c6a3a7e7eb323a64e684"
    end

    on_intel do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.5/pastoralist-darwin-amd64"
      sha256 "e5d5724ccc1132a3daa8f981ea570a9858e86f60d6717b45193994f593b21a02"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.5/pastoralist-linux-arm64"
      sha256 "dc4459a4b5492167246880e304c9cb422647878d0eff19c28a363f576147bbde"
    end

    on_intel do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.5/pastoralist-linux-amd64"
      sha256 "b8ebf7be16ebe4090538b64c3c7ed67c7614bad155198cd9e94c841f0b50bc8e"
    end
  end

  def install
    bin.install Dir["pastoralist-*"].first => "pastoralist"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pastoralist --version")
  end
end
