# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pastoralist < Formula
  desc "Audit, secure, and clean up package manager overrides"
  homepage "https://jeffry.in/pastoralist/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.6/pastoralist-darwin-arm64"
      sha256 "e5c75262a2e3341e9ad06ff3fdce7624a8324bdc054ba3db5a456c6ea04eeeb2"
    end

    on_intel do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.6/pastoralist-darwin-amd64"
      sha256 "2c92831b65c60dfada37f9e17e2ea9edd666591fb1841e7f7b88f83555bd81ba"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.6/pastoralist-linux-arm64"
      sha256 "c3a628a2a9e91f22e470594aa1b4a43542cc474d7e524ba88b1c63704311fabe"
    end

    on_intel do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.6/pastoralist-linux-amd64"
      sha256 "2d325800c6feef38b745eb64c538f685d5cd28792b03d89e0b9e6f3d811bed70"
    end
  end

  def install
    bin.install Dir["pastoralist-*"].first => "pastoralist"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pastoralist --version")
  end
end
