# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pastoralist < Formula
  desc "Audit, secure, and clean up package manager overrides"
  homepage "https://jeffry.in/pastoralist/"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.8/pastoralist-darwin-arm64"
      sha256 "f5767e3d7f0fa542d667ee1fa516190a0223bfc94a9af038fdf0e8b40c6eecf8"
    end

    on_intel do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.8/pastoralist-darwin-amd64"
      sha256 "6205556d8b61faa5ce7918934ccb79f2a953783e073ab95b52647de1b4c715e5"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.8/pastoralist-linux-arm64"
      sha256 "b5281fc12ee3de3d9388da72947df6dc425adee6ba4145884df042dbc9241465"
    end

    on_intel do
      url "https://github.com/yowainwright/pastoralist/releases/download/v1.13.8/pastoralist-linux-amd64"
      sha256 "9a53b0d7ec48288895ec22bed8f01a277c43861e291e4fe13da49d37328260d7"
    end
  end

  def install
    bin.install Dir["pastoralist-*"].first => "pastoralist"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pastoralist --version")
  end
end
