# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pk < Formula
  desc "Safe-by-default local development process cleanup"
  homepage "https://github.com/yowainwright/pk"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.0/pk-darwin-arm64"
      sha256 "50d0781521d20b8d68a695e9c7f7a843aa045d7b233c1f848b9b631c1f643256"
    end

    on_intel do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.0/pk-darwin-amd64"
      sha256 "85def9067bb173b5399fb654220c7f87dd46e0787f2d07e7c3a54e5715b9ef22"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.0/pk-linux-arm64"
      sha256 "b4caa624805c25604851e03e5a945636d8af424f6007a5146ed1c7cd6d300854"
    end

    on_intel do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.0/pk-linux-amd64"
      sha256 "ca9f626de8a094c356826bf8e6960e92b0090cf6febd2234c98a2df238a4925a"
    end
  end

  def install
    bin.install Dir["pk-*"].first => "pk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pk --version")
  end
end
