# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pk < Formula
  desc "Safe-by-default local development process cleanup"
  homepage "https://github.com/yowainwright/pk"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pk/releases/download/v0.1.0/pk-darwin-arm64"
      sha256 "83e2ea68936beb99a6c07d29205f1b0c696b00601dbe4d2810d3e88f7768943e"
    end

    on_intel do
      url "https://github.com/yowainwright/pk/releases/download/v0.1.0/pk-darwin-amd64"
      sha256 "ee2442830367f5941b4fe2e6df16472d7e47e9603e6be6c4052724a0a6205d79"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pk/releases/download/v0.1.0/pk-linux-arm64"
      sha256 "ec588f5106d37117485f1278f5472aa5836694f1b544f90237245cb613a2197b"
    end

    on_intel do
      url "https://github.com/yowainwright/pk/releases/download/v0.1.0/pk-linux-amd64"
      sha256 "9397fe36d8f1f7d8ce1267f7a4b82e27462076226a38ca29a9e4484a49166d23"
    end
  end

  def install
    bin.install Dir["pk-*"].first => "pk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pk --version")
  end
end
