# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pk < Formula
  desc "Safe-by-default local development process cleanup"
  homepage "https://github.com/yowainwright/pk"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.1/pk-darwin-arm64"
      sha256 "1999621a0af4c4c36a2bb787ca43b1fac89c8acd99212a50efe2f8691282fdf5"
    end

    on_intel do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.1/pk-darwin-amd64"
      sha256 "be3def0b7715f9f822aa0d1dcd346d8e42fa963859f964a006ad966083d79048"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.1/pk-linux-arm64"
      sha256 "dce1f2f7b3df23d74255c8304916f260e14cc06734d4ec63c68fd14c9e3b36c8"
    end

    on_intel do
      url "https://github.com/yowainwright/pk/releases/download/v0.2.1/pk-linux-amd64"
      sha256 "0b8cab81873e61f25775e576efce9758fd19dcf65c7bc3850ce02be19c5b964f"
    end
  end

  def install
    bin.install Dir["pk-*"].first => "pk"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pk --version")
  end
end
