# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pre < Formula
  desc "Security proxy for package managers"
  homepage "https://github.com/yowainwright/pre"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.1/pre-darwin-arm64"
      sha256 "2f897823911f937074580712bfcc3116e3b33e6ffeee6ca56fa0301b78208293"
    end

    on_intel do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.1/pre-darwin-amd64"
      sha256 "b902d097bfb5dd53bc358d8628736ea2798b3b5a65ea705ed13ccf61a0dca48a"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.1/pre-linux-arm64"
      sha256 "7939aff6de7a93159d80381e9c8f1e2aede12c193f43257e2363bb07022fe921"
    end

    on_intel do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.1/pre-linux-amd64"
      sha256 "2d6e8ab043f9cf29d96b30fba51fa5dbe7143dbec59461acc10c89e65c5883ab"
    end
  end

  def install
    bin.install Dir["pre-*"].first => "pre"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pre --version")
  end
end
