# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pre < Formula
  desc "Security proxy for package managers"
  homepage "https://github.com/yowainwright/pre"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.0/pre-darwin-arm64"
      sha256 "5784686bbea6381cf1ecb34111526b7adbc2a379605e1ac5eeeac3f3a8fa2a2d"
    end

    on_intel do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.0/pre-darwin-amd64"
      sha256 "effcfe0f9bfe47072fe74fd28e7966cd545a623af15ed7c0eaca0191738deaac"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.0/pre-linux-arm64"
      sha256 "a22f7cd777b21384c40466b2a85d91809695afc5862d7d7265e21293b13025af"
    end

    on_intel do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.0/pre-linux-amd64"
      sha256 "71709bb2a9b39d578fabc1ab067cf6682cb5c47834c326176063b6b89af9de87"
    end
  end

  def install
    bin.install Dir["pre-*"].first => "pre"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pre --version")
  end
end
