# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class Pre < Formula
  desc "Security proxy for package managers"
  homepage "https://github.com/yowainwright/pre"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.2/pre-darwin-arm64"
      sha256 "5c8af59018366c6007876e2b34aa5faff0b080d3a364aaa6d7d5a5c7cb320d1d"
    end

    on_intel do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.2/pre-darwin-amd64"
      sha256 "f73dfa13d6c68b440f05771dd131d56722825ed924641db52c47b1818788014d"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.2/pre-linux-arm64"
      sha256 "08aed6dabb2378d02c7e43fb677591e83816369e714805e0e7e2940f35402ffe"
    end

    on_intel do
      url "https://github.com/yowainwright/pre/releases/download/v0.6.2/pre-linux-amd64"
      sha256 "10af275059d3b8363b64c3d3a647483dd5ab3445e2869ed693a9a3cc77a76e68"
    end
  end

  def install
    bin.install Dir["pre-*"].first => "pre"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/pre --version")
  end
end
