# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class ShellcheckLegibility < Formula
  desc "Shell legibility checks that sit beside ShellCheck"
  homepage "https://github.com/yowainwright/shellcheck_legibility"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.3.0/shellcheck-legibility-darwin-arm64.tar.gz"
      sha256 "3362af21d120193a3a8ecf30c36d7116f4b8bd5f4c6abd44e5e61e355df083f5"
    end

    on_intel do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.3.0/shellcheck-legibility-darwin-amd64.tar.gz"
      sha256 "521b94af5887e72474b18df61ade11bb7f6cc9167696b895052d2203e51285cb"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.3.0/shellcheck-legibility-linux-arm64.tar.gz"
      sha256 "567a5d54912cc7fa5c9f4dc72e34c5ec88d562b8e7eef0cce2ac7e1c38470725"
    end

    on_intel do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.3.0/shellcheck-legibility-linux-amd64.tar.gz"
      sha256 "a8b7888e00627dc88dc902cdfeab13195a7d7b1e6420a27e49d7cdb5a8f6c368"
    end
  end

  def install
    bin.install "shellcheck-legibility"
    pkgshare.install "LICENSE", "LICENSES"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shellcheck-legibility --version")
  end
end
