# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class ShellcheckLegibility < Formula
  desc "Shell legibility checks that sit beside ShellCheck"
  homepage "https://github.com/yowainwright/shellcheck_legibility"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.2.3/shellcheck-legibility-darwin-arm64.tar.gz"
      sha256 "161c38c8c78ab8e8af4bfb0667b02cb78d09bfe999f4b70c6f512b8e989f8b09"
    end

    on_intel do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.2.3/shellcheck-legibility-darwin-amd64.tar.gz"
      sha256 "161c38c8c78ab8e8af4bfb0667b02cb78d09bfe999f4b70c6f512b8e989f8b09"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.2.3/shellcheck-legibility-linux-arm64.tar.gz"
      sha256 "161c38c8c78ab8e8af4bfb0667b02cb78d09bfe999f4b70c6f512b8e989f8b09"
    end

    on_intel do
      url "https://github.com/yowainwright/shellcheck_legibility/releases/download/v0.2.3/shellcheck-legibility-linux-amd64.tar.gz"
      sha256 "161c38c8c78ab8e8af4bfb0667b02cb78d09bfe999f4b70c6f512b8e989f8b09"
    end
  end

  def install
    bin.install "shellcheck-legibility"
    pkgshare.install "LICENSE", "LICENSES"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/shellcheck-legibility --version")
  end
end
