# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class SrcLint < Formula
  desc "Enforce import boundaries across services and packages"
  homepage "https://github.com/yowainwright/src-lint"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.2/src-lint-darwin-arm64"
      sha256 "4d29bff40c255ed007d3c562e9d5aab6db6c56f0180b3cfc5f1979a62daac388"
    end

    on_intel do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.2/src-lint-darwin-amd64"
      sha256 "3837d437a05d6e13c635b05c32b72511529b4215721bd04f9902ea77804485c1"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.2/src-lint-linux-arm64"
      sha256 "b3c5dee527adbbffff214cae355a3be0e59e28c297fdc6a7797e5dbf08f7038e"
    end

    on_intel do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.2/src-lint-linux-amd64"
      sha256 "ce9a289747661aeff1dd242e9f35c586ee303d253c478c4ab50d1a59a5e27459"
    end
  end

  def install
    bin.install Dir["src-lint-*"].first => "src-lint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/src-lint --version")
  end
end
