# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class SrcLint < Formula
  desc "Enforce import boundaries across services and packages"
  homepage "https://github.com/yowainwright/src-lint"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.0/src-lint-darwin-arm64"
      sha256 "99c65b65c4f4367abdd1967976d937bc0f9a0fec319266e6e0ff558709460a94"
    end

    on_intel do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.0/src-lint-darwin-amd64"
      sha256 "72548f838f19013ed505092e4cc452720c8f067d23a12ca86c4d4e0f067ddd67"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.0/src-lint-linux-arm64"
      sha256 "ccde4c09e1ab42f85242cc5a4c441259da4a6ef2b3c7d8b1be40b0d7d5aeda46"
    end

    on_intel do
      url "https://github.com/yowainwright/src-lint/releases/download/v0.1.0/src-lint-linux-amd64"
      sha256 "0d6a6cd61e428f9c99572f452f2512359b87545a28f5afc685a5db624175b3fd"
    end
  end

  def install
    bin.install Dir["src-lint-*"].first => "src-lint"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/src-lint --version")
  end
end
