# frozen_string_literal: true

# This file was generated by scripts/update-formula. DO NOT EDIT.
class StructLint < Formula
  desc "Check declaration and function order in source files"
  homepage "https://github.com/yowainwright/struct-lint"
  license "MIT"

  on_macos do
    on_arm do
      url "https://github.com/yowainwright/struct-lint/releases/download/v0.1.0/struct-lint-darwin-arm64.tar.gz"
      sha256 "0d8596f08cfa6cfd25010ce88b15e2e7e897dc58927c2934381db75c08b9a5e6"
    end

    on_intel do
      url "https://github.com/yowainwright/struct-lint/releases/download/v0.1.0/struct-lint-darwin-amd64.tar.gz"
      sha256 "bf1e775d0bf00927708eb8443ebdcde8327bd6df63108250845d92f1d3e0b451"
    end
  end

  on_linux do
    on_arm do
      url "https://github.com/yowainwright/struct-lint/releases/download/v0.1.0/struct-lint-linux-arm64.tar.gz"
      sha256 "c45b43c018f0c858ba961aa60878a18bf55319b4d97c41cf0ebe68ad6ca739a3"
    end

    on_intel do
      url "https://github.com/yowainwright/struct-lint/releases/download/v0.1.0/struct-lint-linux-amd64.tar.gz"
      sha256 "a565e3af83de0276579b46eeac8d918b537a90ad6724b243001fe65cd75d9344"
    end
  end

  def install
    bin.install "struct-lint"
    pkgshare.install "LICENSE", "LICENSES"
  end

  test do
    assert_match version.to_s, shell_output("#{bin}/struct-lint --version")
  end
end
