# frozen_string_literal: true

require "json"

module TapRelease
  ROOT = File.expand_path("../..", __dir__)
  README_START = "<!-- formulas:start -->"
  README_END = "<!-- formulas:end -->"
  README_PATTERN = /#{Regexp.escape(README_START)}.*?#{Regexp.escape(README_END)}/m
  TARGETS = %w[
    darwin-arm64
    darwin-amd64
    linux-arm64
    linux-amd64
  ].freeze
  REQUIRED_BREW_FIELDS = %w[
    name
    class_name
    command
    repo
    desc
    homepage
    license
    version
    asset_prefix
    managed
  ].freeze

  def self.brew_path(name)
    File.join(ROOT, "brews", "#{name}.json")
  end

  def self.brew_files
    Dir[File.join(ROOT, "brews", "*.json")].sort
  end

  def self.read_brew(path)
    JSON.parse(File.read(path))
  end

  def self.brew_rows
    brew_files.filter_map do |path|
      data = read_brew(path)
      next unless data.fetch("readme", false)

      [data.fetch("command"), data.fetch("desc")]
    end.sort_by(&:first)
  end

  def self.readme_block
    rows = brew_rows.map { |command, desc| "| `#{command}` | #{desc} |" }

    [
      README_START,
      "<!-- generated by scripts/update-formula; do not edit -->",
      "| Formula | Description |",
      "|---------|-------------|",
      *rows,
      README_END
    ].join("\n")
  end

  def self.replace_readme_block(readme)
    return nil unless readme.scan(README_START).count == 1
    return nil unless readme.scan(README_END).count == 1

    readme.sub(README_PATTERN) { readme_block }
  end
end
